### ISSUE TITLE
Set CircleCI to deploy :nightly label on every master commit

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-search#40]
Right now we've only building containers on tags.
```
  search_build:
    jobs:
      - build_project:
          filters:
            tags:
              only: /.*/
```
https://github.com/cyberFund/cyber-search/blob/master/.circleci/config.yml

And deploy on release tag only:
```
      - deploy_search_api_image:
          <<: *release_filter
          requires:
             - build_project
```

We need to build on every commit (test build) and every commit in master as `:nightly`.

**Comment by abitrolly** [comment]
@YodaMike

**Comment by abitrolly** [comment]
Correction. We build on tags *and* branches. See https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
```
      - build_project:
          filters:
            tags:
              only: /.*/
```
Need only to fix deployment for `:nightly`.
